<a href="https://colab.research.google.com/github/Navnidhi-gandhi07/UCS420--P/blob/main/assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a dataset as follow in the table.

In [ ]:
import pandas as pd
dataset={
    'tid':[1,2,3,4,5,6,7,8,9,10],
    'refund':["yes","no","no","yes","no","no","yes","no","no","no"],
    'marital status':["single","married","single","married","divorced","married","divorced","single","married","single"],
    'taxable income':["125k","100k","70k","120k","95k","60k","220k","85k","75k","90k"],
    'cheat':["no","no","no","no","yes","no","no","yes","no","yes"]
}
df=pd.DataFrame(dataset)
print(df)

   tid refund marital status taxable income cheat
0    1    yes         single           125k    no
1    2     no        married           100k    no
2    3     no         single            70k    no
3    4    yes        married           120k    no
4    5     no       divorced            95k   yes
5    6     no        married            60k    no
6    7    yes       divorced           220k    no
7    8     no         single            85k   yes
8    9     no        married            75k    no
9   10     no         single            90k   yes

Q.2 From the above table that you have created, locate row 0, 4, 7 and 8 using DataFrame.

In [ ]:
print(df.loc[0],"\n")

print(df.loc[4],"\n")
print(df.loc[7],"\n")
print(df.loc[8])

tid                    1
refund               yes
marital status    single
taxable income      125k
cheat                 no
Name: 0, dtype: object

tid                      5
refund                  no
marital status    divorced
taxable income         95k
cheat                  yes
Name: 4, dtype: object

tid                    8
refund                no
marital status    single
taxable income       85k
cheat                yes
Name: 7, dtype: object

tid                     9
refund                 no
marital status    married
taxable income        75k
cheat                  no
Name: 8, dtype: object

Navigate the DataFrame and do the following task for the table created in question 1:
1. Select row from index 3 to 7.
2. Select row from index 4 to 8, and column 2 to 4.
3. Select all rows with column index 1 to 3 (include index 3 during selection).

In [ ]:
df.iloc[3:8]

   tid refund marital status taxable income cheat
3    4    yes        married           120k    no
4    5     no       divorced            95k   yes
5    6     no        married            60k    no
6    7    yes       divorced           220k    no
7    8     no         single            85k   yes

In [ ]:
df.iloc[4:9,2:5]

  marital status taxable income cheat
4       divorced            95k   yes
5        married            60k    no
6       divorced           220k    no
7         single            85k   yes
8        married            75k    no

In [ ]:
df.iloc[:,1:4]

  refund marital status taxable income
0    yes         single           125k
1     no        married           100k
2     no         single            70k
3    yes        married           120k
4     no       divorced            95k
5     no        married            60k
6    yes       divorced           220k
7     no         single            85k
8     no        married            75k
9     no         single            90k

Read a csv file and display its first five rows.
Note-: Download dataset from https://www.kaggle.com/datasets/uciml/iris)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Iris.csv to Iris.csv

In [ ]:

df = pd.read_csv('Iris.csv')
print(df.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Q.5 From the csv file (uploaded in the Q.4) delete row 4, and delete column 3. Display the
result.

In [ ]:
 df.drop(3, axis=0, inplace=True)
 df.drop(df.columns[2], axis=1, inplace=True)
 print(df)

      Id  SepalLengthCm  PetalWidthCm         Species
0      1            5.1           0.2     Iris-setosa
1      2            4.9           0.2     Iris-setosa
2      3            4.7           0.2     Iris-setosa
5      6            5.4           0.4     Iris-setosa
6      7            4.6           0.3     Iris-setosa
..   ...            ...           ...             ...
145  146            6.7           2.3  Iris-virginica
146  147            6.3           1.9  Iris-virginica
147  148            6.5           2.0  Iris-virginica
148  149            6.2           2.3  Iris-virginica
149  150            5.9           1.8  Iris-virginica

[148 rows x 4 columns]

In [ ]:

data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": ["2020-03-15", "2017-07-19", "2013-06-01", "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}

df = pd.DataFrame(data)
df.to_csv("employees.csv", index=False)

In [ ]:
import pandas as pd
df = pd.read_csv("employees.csv")

print("Shape ", df.shape)

print(df.info())

print(df.describe())

print(df.head())

print(df.tail(3))

average= df["Salary"].mean()
total = df["Bonus"].sum()
youngest = df["Age"].min()
highest = df["Rating"].max()

print("\nAverage Salary:", average)
print("Total Bonus Paid:", total)
print("Youngest Employee's Age:", youngest)
print("Highest Performance Rating:", highest)

sortdf = df.sort_values(by="Salary", ascending=False)
print("\nDataFrame sorted by Salary (descending):")
print(sortdf)
print("\nMissing Values ")
print(df.isnull().sum())

df.rename(columns={"Employee_ID": "ID"}, inplace=True)
print(df.head())
print("\nEmployees with more than 5 years of experience:")
print(df[df["Years_of_Experience"] > 5])

print("\nEmployees in the IT department:")
print(df[df["Department"] == "IT"])

df["Tax"] = df["Salary"] * 0.1
print("\nDataFrame with Tax Column:")
print(df)

df.to_csv("modified_employees.csv", index=False)
print("\nModified DataFrame saved to 'modified_employees.csv'")

Shape  (5, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes
None
       Employee_ID        Age       Salary  Years_of_Experience   Bonus  \
count     5.000000   5.000000      5.00000             5.000000     5.0
mean    103.000000  34.000000  60000.00000             7.400000  5500.0
std       1.581139   5.612486   7905.69415             3.847077  1000.0
min     101.000000  28.000000  50000.00000             3.000000  4500.0
25%     102.000000  29.000000  55000.00000             4.000000  5000.0
50%     103.000000  34.000000  60000.00000             8.000000  5000.0
75%     104.000000  38.000000  65000.00000            10.000000  6000.0
max     105.000000  41.000000  70000.00000            12.000000  7000.0

         Rating
count  5.000000
mean   4.100000
std    0.494975
min    3.500000
25%    3.800000
50%    4.000000
75%    4.500000
max    4.700000
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

Average Salary: 60000.0
Total Bonus Paid: 27500
Youngest Employee's Age: 28
Highest Performance Rating: 4.7

DataFrame sorted by Salary (descending):
   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
3          104    Diana  Marketing   28   55000                    3
0          101    Alice         HR   29   50000                    4

  Joining_Date  Gender  Bonus  Rating
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
4   2010-11-25    Male   5000     3.5
3   2021-02-10  Female   4500     4.7
0   2020-03-15  Female   5000     4.5

Missing Values
Employee_ID            0
Name                   0
Department             0
Age                    0
Salary                 0
Years_of_Experience    0
Joining_Date           0
Gender                 0
Bonus                  0
Rating                 0
dtype: int64
    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
0  101    Alice         HR   29   50000                    4   2020-03-15
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
3  104    Diana  Marketing   28   55000                    3   2021-02-10
4  105   Edward      Sales   38   60000                   12   2010-11-25

   Gender  Bonus  Rating
0  Female   5000     4.5
1    Male   7000     4.0
2    Male   6000     3.8
3  Female   4500     4.7
4    Male   5000     3.5

Employees with more than 5 years of experience:
    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25

  Gender  Bonus  Rating
1   Male   7000     4.0
2   Male   6000     3.8
4   Male   5000     3.5

Employees in the IT department:
    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01

  Gender  Bonus  Rating
1   Male   7000     4.0
2   Male   6000     3.8

DataFrame with Tax Column:
    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
0  101    Alice         HR   29   50000                    4   2020-03-15
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
3  104    Diana  Marketing   28   55000                    3   2021-02-10
4  105   Edward      Sales   38   60000                   12   2010-11-25

   Gender  Bonus  Rating     Tax
0  Female   5000     4.5  5000.0
1    Male   7000     4.0  7000.0
2    Male   6000     3.8  6500.0
3  Female   4500     4.7  5500.0
4    Male   5000     3.5  6000.0

Modified DataFrame saved to 'modified_employees.csv'